name: Build and Push Docker Image to AWS ECR

on:
  workflow_dispatch:

jobs:
  publish-docker-image:
    runs-on: ubuntu-latest
    env:
      REPOSITORY: '<REPOSITORY>'
      IMAGE_VERSION: 'latest'
      AWS_AK: ${{ secrets.<AWS ACCOUNT ACCESS KEY> }}
      AWS_SK: ${{ secrets.<AWS ACCOUNT SECRET KEY> }}
    steps:
    - uses: actions/checkout@v2
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with: 
         aws-access-key-id: ${{ env.AWS_AK }}
         aws-secret-access-key: ${{ env.AWS_SK }}
         aws-region: eu-west-1
    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1
    - name: Docker Build and Push to Amazon ECR
      env:
        ECR_URL: ${{ steps.login-ecr.outputs.registry }}/${{ env.REPOSITORY }}
      run: |
        docker build -t ${{ env.ECR_URL }}:${{ env.IMAGE_VERSION }} .
        docker push ${{ env.ECR_URL }}:${{ env.IMAGE_VERSION }}
