name: CloudFormation Deployer

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Enter environment for deployment: dev, qa or pro'
        required: true
        default: 'dev'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Credentials to DEV Environment
        if: ${{ github.event.inputs.environment=='dev' }}
        run: | 
           echo "AKID=${{ secrets.CHEM_AWS_DEV_AK }}" >> $GITHUB_ENV
           echo "SKID=${{ secrets.CHEM_AWS_DEV_SK }}">> $GITHUB_ENV
      - name: Credentials to QA Environment
        if: ${{ github.event.inputs.environment=='qa' }}
        run: | 
           echo "AKID=${{ secrets.CHEM_AWS_QA_AK }}" >> $GITHUB_ENV
           echo "SKID=${{ secrets.CHEM_AWS_QA_SK }}">> $GITHUB_ENV           
      - name: Credentials to PRO Environment
        if: ${{ github.event.inputs.environment=='pro' }}
        run: | 
           echo "AKID=${{ secrets.CHEM_AWS_PRO_AK }}" >> $GITHUB_ENV
           echo "SKID=${{ secrets.CHEM_AWS_PRO_SK }}">> $GITHUB_ENV          
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with: 
          aws-access-key-id: ${{ env.AKID }}
          aws-secret-access-key: ${{ env.SKID }}
          aws-region: eu-west-1
      - name: get aws caller indentity
        run:  aws sts get-caller-identity
      - name: cloudformation-deployer action
        uses: cepsadigital/github-action-devops-cloudformation-deployer@1.0.0
        with:
          githubtoken: ${{ secrets.ROBOT_TOKEN }}
          cfnparams: iac
