
# This is a basic workflow to help you get started with Actions

name: CEPSA-get-caller-indentity
  
on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Enter environment for deployment. Default is dev'
        required: true
        default: 'dev'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  run script:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
  
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2    
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with: 
          aws-access-key-id: ${{ secrets.AWS_DEV_AK }}
          aws-secret-access-key: ${{ secrets.AWS_DEV_SK }}
          aws-region: eu-west-1
      # Runs a set of commands using the runners shell
      - name: get aws caller indentity
        run:  aws sts get-caller-identity


