# Workflow: CEPSA - Upload Python Package to Artifactory
# Description: This is a basic workflow for packaging python libraries and uploading them to Artifactory.
# Actions:             
# - Run Tests and Code Analysis
# https://github.com/cepsadigital/github-action-devops-test-and-code-analysis
# - SonarQube Scan
# https://github.com/cepsadigital/github-action-devops-sonar-scan
# - Build and Publish to Artifactory
# https://github.com/cepsadigital/github-action-devops-upload-artifactory

name: CEPSA - Upload Python Package to Artifactory

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.6'
    - name: Run Tests and Code Analysis
      uses: cepsadigital/github-action-devops-test-and-code-analysis@master 
      with:
        source-code-folder-name: 'src'
    - name: SonarQube Scan
      uses: cepsadigital/github-action-devops-sonar-scan@master
      with:
        host: ${{ secrets.TD_SONAR_HOST }}
        login: ${{ secrets.TD_SONAR_USER }}
        password: ${{ secrets.TD_SONAR_PSW }} 
    - name: Build and Publish to Artifactory
      uses: cepsadigital/github-action-devops-upload-artifactory@master
      with:
        repository-host: https://cepsa.jfrog.io/artifactory/api/pypi/td-pypi
        artifactory-user: ${{ secrets.TD_ARTIFACTORY_USER }}
        artifactory-token: ${{ secrets.TD_ARTIFACTORY_TOKEN }}
