# This is a basic workflow to help you get started with Actions

name: CEPSA - Upload Python Package to Artifactory

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.6'
    - name: Run tests
      run: |
        python -m pip install --upgrade pip
        pip install tox && tox
    - name: Static Code Analysis
      run: |
        mkdir -p reports
        pip install pylint bandit
        pylint -r y -s y -f json --exit-zero src/ --exit-zero > reports/pylint.json
        bandit -r src/ -f json -o reports/bandit.json || true
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install setuptools wheel twine
    - name: SonarQube Scan
      uses: cepsadigital/devops-sonar-github-action@master
      with:
        host: ${{ secrets.TD_SONAR_HOST }}
        login: ${{ secrets.TD_SONAR_USER }}
        password: ${{ secrets.TD_SONAR_PSW }}         
    - name: Build and publish
      env:        
        ARTIFACTORY_PWD: ${{ secrets.TD_ARTIFACTORY_TOKEN }}
      run: |
        python setup.py sdist bdist_wheel
        twine upload --repository-url https://cepsa.jfrog.io/artifactory/api/pypi/td-pypi-local -u jenkins -p ${ARTIFACTORY_PWD} --non-interactive dist/*
