# Workflow: Upload Python Library to Artifactory - CEPSA
# Description: This is a basic workflow for packaging python libraries and uploading them to Artifactory.
# Actions: 
# - Set up Python version
# https://github.com/actions/setup-python
# - Run Python Tests and Code Analysis
# https://github.com/cepsadigital/github-action-devops-python-testing
# - SonarQube Scan
# https://github.com/cepsadigital/github-action-devops-sonar-scan
# - Upload Python Library to Artifactory
# https://github.com/cepsadigital/github-action-devops-python-upload-artifactory

name: Upload Python Library to Artifactory - CEPSA

on:
  workflow_dispatch:
  push:
    branches:
      - 'releases/**'
    tags:
      - '*'

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      ARTIFACTORY_TD_PYTHON_REPOSITORY_VIRTUAL: td-pypi
      ARTIFACTORY_TD_PYTHON_REPOSITORY_LOCAL: td-pypi-local
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.6'
    - name: Run Python Tests and Code Analysis
      uses: cepsadigital/github-action-devops-python-testing@1.1.0
      with:
        source-code-folder-name: 'src'
        artifactory-user: ${{ secrets.TD_ARTIFACTORY_USER }}
        artifactory-psw: ${{ secrets.TD_ARTIFACTORY_PSW }}
    - name: SonarQube Scan
      uses: cepsadigital/github-action-devops-sonar-scan@1.0.1
      with:
        host: ${{ secrets.TD_SONAR_HOST }}
        login: ${{ secrets.TD_SONAR_USER }}
        password: ${{ secrets.TD_SONAR_PSW }}
    - name: Calculate Version
      run: |              
        if [[ $GITHUB_REF == *"develop"* ]]; then
          PACKAGE_VERSION="$(date '+%Y.%m.%d%H%M%S')"
          # It is assumed that repository and package have the same name
          sed -i.bak -e "s/__version__.*/__version__ = '${PACKAGE_VERSION}'/g" ${GITHUB_WORKSPACE}/${GITHUB_WORKSPACE##*/}/__init__.py
        fi        
        if [[ $GITHUB_REF == *"release/"* ]]; then
          TAG=${GITHUB_REF##*/}
          DATE="$(date '+%Y%m%d%H%M%S')"
          PACKAGE_VERSION="${TAG}rc${DATE}"
          # It is assumed that repository and package have the same name
          sed -i.bak -e "s/__version__.*/__version__ = '${PACKAGE_VERSION}'/g" ${GITHUB_WORKSPACE}/${GITHUB_WORKSPACE##*/}/__init__.py
        fi
        if [[ $GITHUB_REF == *"tags"* ]]; then
          PACKAGE_VERSION=${GITHUB_REF##*/}
          NAME_RC_MATCH="${GITHUB_WORKSPACE##*/}*rc*"
          items=`curl -u ${{ secrets.TD_ARTIFACTORY_USER }}:${{ secrets.TD_ARTIFACTORY_PSW }} -X POST -H "content-type: text/plain" https://cepsa.jfrog.io/artifactory/api/search/aql -d 'items.find({"repo": "${{ env.ARTIFACTORY_TD_PYTHON_REPOSITORY_LOCAL }}"},{"name":{"$match":"'"$NAME_RC_MATCH"'"}}).sort({"$desc" : ["repo","name"]}).limit(2)'`
          items_list=$(echo ${items} | jq '.results')

          for row in $(echo "${items_list}" | jq -r '.[] | @base64'); do
              _jq() {
                echo ${row} | base64 --decode | jq -r ${1}
              }
              path=$(_jq '.path')
              name=$(_jq '.name')
              if [[ $name == *".tar.gz"* ]]; then
                new_path="${GITHUB_WORKSPACE##*/}/${PACKAGE_VERSION}/${GITHUB_WORKSPACE##*/}-${PACKAGE_VERSION}.tar.gz"
              else
                new_path="${GITHUB_WORKSPACE##*/}/${PACKAGE_VERSION}/${GITHUB_WORKSPACE##*/}-${PACKAGE_VERSION}-py3-none-any.whl"    
              fi
              curl -u ${{ secrets.TD_ARTIFACTORY_USER }}:${{ secrets.TD_ARTIFACTORY_PSW }} -X POST https://cepsa.jfrog.io/artifactory/api/copy/td-pypi-local/${path}/${name}?to=/td-pypi-local/${new_path}
          done
      #   DELETE RELEASE CANDIDATE VERSION
      #   curl -u ${{ secrets.TD_ARTIFACTORY_USER }}:${{ secrets.TD_ARTIFACTORY_PSW }} -X DELETE https://cepsa.jfrog.io/artifactory/td-pypi-local/${path}          
        fi                
    - name: Upload Python Library to Artifactory
      uses: cepsadigital/github-action-devops-python-upload-artifactory@1.0.0
      with:
        repository-name: ${{ env.ARTIFACTORY_TD_PYTHON_REPOSITORY_VIRTUAL }}
        artifactory-user: ${{ secrets.TD_ARTIFACTORY_USER }}
        artifactory-psw: ${{ secrets.TD_ARTIFACTORY_PSW }}
        artifactory-host: https://cepsa.jfrog.io
