# Workflow: CEPSA - Upload Python Package to Artifactory
# Description: This is a basic workflow for packaging python libraries and uploading them to Artifactory.
# Actions:             
# - Run Python Tests and Code Analysis
# https://github.com/cepsadigital/github-action-devops-python-testing
# - SonarQube Scan
# https://github.com/cepsadigital/github-action-devops-sonar-scan
# - Upload Python Package to Artifactory
# https://github.com/cepsadigital/github-action-devops-python-upload-artifactory

name: CEPSA - Upload Python Package to Artifactory

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.6'
    - name: Run Python Tests and Code Analysis
      uses: cepsadigital/github-action-devops-python-testing@1.0.0
      with:
        source-code-folder-name: 'src'
    - name: SonarQube Scan
      uses: cepsadigital/github-action-devops-sonar-scan@1.0.0
      with:
        host: ${{ secrets.TD_SONAR_HOST }}
        login: ${{ secrets.TD_SONAR_USER }}
        password: ${{ secrets.TD_SONAR_PSW }} 
    - name: Upload Python Package to Artifactory
      uses: cepsadigital/github-action-devops-python-upload-artifactory@1.0.0
      with:
        repository-name: td-pypi
        artifactory-user: ${{ secrets.TD_ARTIFACTORY_USER }}
        artifactory-token: ${{ secrets.TD_ARTIFACTORY_TOKEN }}
