# Workflow: Upload Python Library to Artifactory - CEPSA
# Description: This is a basic workflow for packaging python libraries and uploading them to Artifactory.
# Actions: 
# - Set up Python version
# https://github.com/actions/setup-python
# - Run Python Tests and Code Analysis
# https://github.com/cepsadigital/github-action-devops-python-testing
# - SonarQube Scan
# https://github.com/cepsadigital/github-action-devops-sonar-scan
# - Upload Python Library to Artifactory
# https://github.com/cepsadigital/github-action-devops-python-upload-artifactory

name: Upload Python Library to Artifactory - CEPSA

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.6'
    - name: Run Python Tests and Code Analysis
      uses: cepsadigital/github-action-devops-python-testing@1.0.0
      with:
        source-code-folder-name: 'src'
    - name: SonarQube Scan
      uses: cepsadigital/github-action-devops-sonar-scan@1.0.0
      with:
        host: ${{ secrets.TD_SONAR_HOST }}
        login: ${{ secrets.TD_SONAR_USER }}
        password: ${{ secrets.TD_SONAR_PSW }} 
    - name: Upload Python Library to Artifactory
      uses: cepsadigital/github-action-devops-python-upload-artifactory@1.0.0
      with:
        repository-name: td-pypi
        artifactory-user: ${{ secrets.TD_ARTIFACTORY_USER }}
        artifactory-psw: ${{ secrets.TD_ARTIFACTORY_PSW }}
