# This is a basic workflow to help you get started with Actions

name: CEPSA - Upload Python Package to Artifactory

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run Tests and Code Analysis
      uses: cepsadigital/github-action-devops-test-and-code-analysis@master 
      with:
        source-code-folder-name: 'src'
        tox-filename: 'tox.ini'
        python-version: '3.6'
        requirements-filename: 'requirements.txt'     
    - name: SonarQube Scan
      uses: cepsadigital/github-action-devops-sonar-scan@master       
    - name: Build and publish
      uses: cepsadigital/github-action-devops-upload-artifactory@master
      with:
        repository-host: <VIRTUAL-REPOSITORY-HOST>
